### ISSUE TITLE
Chapter II - graphiqlHapi and graphqlHapi are not defined

### ISSUE THREAD

**Issue by DanStockham** [wesharehoodies/graphql-nodejs-hapi-api#1]
In the tutoria after requiring `hapi-graphql` and your schema and registering your plugins, there is no mention to require graphiqlHapi and graphqlHapi. However, in the source code there is a  dependency for `apollo-server-hapi`

Should that be included in the tutorial? Also, another thing I'm noticing is that when I include apollo dependency, I get this error

`(node:17228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Apollo Server requires options.`

Although the source code doesn't have options when I looked. Also wouldn't the process middleware declared at the bottom of the `index.js` handle the promise rejection?

The final issue I've encountered was with the swagger documentation site. When you try out the post method you get a 500 error because there isn't any content in the request to post.

**Comment by trevorlasn** [comment]
Hey @DanStockham , thanks for the feedback. Just to confirm you are right and I updated the article. Good job, thanks! 👍
